
export const enums = {
    DB_ENUM_TYPE_GAME: 'GAME',
    DB_ENUM_TYPE_CONSOLE: 'CONSOLE',
    DB_ENUM_TYPE_MUSIC_CD: 'MUSIC_CD',
    DB_ENUM_TYPE_BOOK: 'BOOK',
    DB_ENUM_TYPE_OTHER: 'OTHER',
    
    DB_ENUM_STATUS_AVAILABLE: 'AVAILABLE',
    DB_ENUM_STATUS_LENT: 'LENT',
    DB_ENUM_STATUS_LOST: 'LOST',
    DB_ENUM_STATUS_NO_LONGER_HAS: 'NO_LONGER_HAS',

    DB_ENUM_FRIENDSHIP_STATUS_PENDING: 'PENDING',
    DB_ENUM_FRIENDSHIP_STATUS_ACCEPTED: 'ACCEPTED',
    DB_ENUM_FRIENDSHIP_STATUS_BLOCKED: 'BLOCKED',
}
